### ISSUE TITLE
CSS documentation for themes

### ISSUE THREAD

**Issue by nikoheikkila** [careteditor/caret#186]
Hi,

I'd like to make my own preview theme based on the wonderful Cobalt 2 theme made popular by Wes Bos. I copied the _Default.css_ to a new file and wrote following.

```css
.preview {
    background-color: #193549;
    color: #FFF;
   /* Other rules */
}
```

Only the foreground color change is applied, but the background color has no effect. Tried putting it in `body` definition as well, but no help. Is there a proper documentation for theme modification anywhere?

**Comment by erusev** [comment]
Thanks for reporting, we'll investigate and get back to you.

**Comment by astoilkov** [comment]
Hi @nikoheikkila,

In order to change the background color of the preview you could use the code provided below:
```css
:host {
  background: #193549 !important;
}
```

We agree that it is hard to know what exactly should be done to change the background color so we changed the Default and GitHub themes to use the `:host` selector so people creating new themes can easily understand how things like background color could be changed.

Thanks a lot for reporting this.

P.S. Starting from the next release of Caret you will no longer need to add the `!important` in the CSS statement.
