### ISSUE TITLE
No bolds in preview

### ISSUE THREAD

**Issue by ritashugisha** [careteditor/caret#263]
Bolds don't seem to be rendering for me correctly in the preview in release 2.0.0+ on Ubuntu 16.10.

![2.0.0](http://i.imgur.com/NUjDIaN.png)

Here is how 1.15.1 looked...

![1.15.1](http://i.imgur.com/HneQgfs.png)

My settings are the following:

# Preferences

Edit and save to update preferences:

```yaml
font: Roboto
fontSize: 16
lineHeight: 1.73
lineWidth: 72
```

More options coming soon.
