### ISSUE TITLE
PDF font size is large

### ISSUE THREAD

**Issue by Bhendrickx** [careteditor/caret#382]
When exporting any document (including latex) the font of text within the PDF is large. The text spans multiple pages, when it could fit on a single page.

I'm using: 
ubuntu 17.04
Caret 2.1.3

Thanks in advance

**Comment by erusev** [comment]
Thanks, we'll see what we can do

**Comment by BsNoSi** [comment]
You simply can add some CSS to your theme. I solved it this way:

```css
[…]
 @media print {
     body {font-size:12pt;line-height:1.5;} 
    }
```

I tried to add a page footer with page counter, too, but this did not work.
