### ISSUE TITLE
Convert GitHub URL to issue link

### ISSUE THREAD

**Issue by borekb** [careteditor/caret#426]
Just a quick idea for those of us writing a lot of GitHub content in Caret:

Before:

```md
See issue https://github.com/versionpress/versionpress/issues/1243.
```

After invoking context action like "GitHub issue link":

```md
See issue [#1243](https://github.com/versionpress/versionpress/issues/1243).
```

Bonus point (I'm not sure if this is necessary but anyway, will throw the idea around):

There's another context action, "GitHub issue link with repo" which produces:

```md
See issue [versionpress/versionpress#1243](https://github.com/versionpress/versionpress/issues/1243).
```

The context action(s) would be available for URLs that follow the pattern

```
(?<!\]\()https://github\.com/[^\/]+/[^\/]+/(?:issues|pull)/(\d+)
```

**Comment by borekb** [comment]
Seeing the `extension` label (ooooohh), this could probably be achieved by configuration like this (imagine a new section in Preferences.md or something similar):

```yaml
textConversions:
    - match: '(?<!\]\()https://github\.com/[^\/]+/[^\/]+/(?:issues|pull)/(\d+)'
      replace: '[#$1]($0)'
      actionLabel: 'GitHub issue link'
    - match: 'VP'
      replace: 'VersionPress'
      actionLabel: 'VP -> VersionPress'
```
