### ISSUE TITLE
Export to PDF does not honour CSS page size / orientation

### ISSUE THREAD

**Issue by codemonkee** [careteditor/caret#552]
Striping out all CSS (as defined in theme file) except for the following, does not seem to be honoured when exporting as a PDF

```css
@page {
  size: A4 landscape;
}
```

Exporting to HTML first and printing as PDF the page will be A4 size in landscape.
