### ISSUE TITLE
CentOS Cursor Alignment

### ISSUE THREAD

**Issue by Carnivorg** [careteditor/caret#559]
The text cursor is aligned properly for short sentences. For longer sentences the cursor appears to become progressively misaligned with text, up to a point where it appears several characters to the left of where text is actually inserted. The effect appears more pronounced in code blocks.

You can reproduce this issue just by typing a sentence into the Caret editor.

For example, in the image below I've double-clicked the word "layout":

![centos-caret-cursor](https://user-images.githubusercontent.com/11945132/31975958-491254fa-b980-11e7-9049-815e9241b597.png)

I'm using 
* Caret 3.4.6 
* GNOME Shell 3.22.3
* CentOS 7 `centos-release-7-4.1708.el7.centos.x86_64`
* standard settings:

```yaml
useProportionalFontInProse: Roboto # set to false to disable
useLargeFontInHeadings: "Roboto" # set to false to disable
font: "Fira Mono"
fontSize: 15
lineHeight: 1.8
lineWidth: 72
```
