### ISSUE TITLE
RC3, RC4: All heading displayed as H1

### ISSUE THREAD

**Issue by chriskrycho** [careteditor/caret#702]
Just what it says:

<img width="726" alt="screen shot 2018-03-28 at 6 23 49 am" src="https://user-images.githubusercontent.com/2403023/38028580-997c6ad6-3250-11e8-8c33-7b924adff833.png">

Also, you might steal a page from Bear, which switches to **H1** and so on just like this, but as soon as you don't have a trailing space after the heading `#`s, switches *back* to them so you can actually see them to delete them!

**Comment by borekb** [comment]
On Windows and in rc4, this behaves correctly:

![image](https://user-images.githubusercontent.com/101152/38057088-929f7530-32de-11e8-83be-ca3e1eea753d.png)

With that being said, I preferred the old `###`. They feel more "markdown-ey".

**Comment by astoilkov** [comment]
Hi @chriskrycho,

Are you seeing this behavior consistently? I am unable to replicate it.

Thanks in advance.

**Comment by chriskrycho** [comment]
@astoilkov yep, still seeing it on RC4, too.

Settings dump:

~~~markdown
# Preferences

Edit and save to update preferences:

```yaml
proseFontFace: 'Sabon LT Std'
proseFontSize: 19
codeFontFace: "Hack Code"
codeFontSize: 13
lineHeight: 2
lineWidth: 58
tabSize: 2
useClassicTextCursor: true
useLargeFontInHeadings: false
```

Want to see another option? Let us know over [Twitter](https://twitter.com/careteditor) or [email](mailto:contact@caret.io).
~~~

One note: I'm using [Sabon](https://www.myfonts.com/fonts/linotype/sabon/) currently, but the same thing happens regardless of the font I'm using.

OS/hardware info:

- macOS High Sierra 10.13.4
- MacBook Pro (Retina, 15-inch, Mid 2015) / 2.8 GHz i7 / 16 GB RAM
