### ISSUE TITLE
Math environment

### ISSUE THREAD

**Issue by amirhosseindavoody** [careteditor/caret#804]
Under latex standard inline math environments are created using a single `$` like `$x^2$` and an equation environment is created using double `$` such as

```
$$ x^2 $$
```

I am wondering why you chose double and triple dollar signs for each one.

Also, when I create a math block using `$$$ x^2 $$$`, the math block is aligned to the left instead of center aligning.

Thanks for the great and slick looking editor.

**Comment by astoilkov** [comment]
Hi,

We actually support both types of writing style. The only requirement for block math is that you put the `$` signs on seperate lines.

![image](https://user-images.githubusercontent.com/884810/45144198-1b08c280-b1c6-11e8-9167-da4f47d249a0.png)

Regarding the alignment of math blocks: You can actually change this by modifying the preview theme. If you don't know how this is done you can write back and I can explain it.

**Comment by amirhosseindavoody** [comment]
@astoilkov Thanks for the reply. I don't know how to change the alignment of math blocks. I appreciate it if you could explain how to do it.

**Comment by amirhosseindavoody** [comment]
@astoilkov I think I figured how to change the alignment. I need to change `text-align: left` to `text-align: center` in the template css file under `.katex-display` rule:

```css
/* Math
   ---------------- */

.katex-display {
  padding: 0.6em 0;
  font-size: 1.2em;
  overflow-x: auto;
  border-radius: 4px;
  margin-bottom: 28px;
  text-align: center;
}
```
